ethereum/portal-network-specs

witness.md
This is the first draft of a spec of the block witness format.
A couple of points about it:
(1) It is based on the real witness format that is currently used in turbo-geth (and its serialization was used to measure data in [the latest blog post](https://medium.com/@mandrigin/semi-stateless-initial-sync-experiment-897cc9c330cb) I wrote). There are a couple of minor differences to keep abstractions more clean (introduction of `CodeNode` and removal of one instruction). So using this format you can actually rebuild tries to run block on Ethereum mainnet.
(2) The witness execution process isn't implemented exactly as stated here, we use a stack machine to execute the witness. I will work on a reference implementation of this "substitution" approach now.
(3) I'm very open to any suggestions. …
=> Witness Specification

witness.md
This pull request contains some minor editorial changes to improve the clarity of the spec. I have also added links for  CBOR and Endians for readers who are unfamiliar with Big Endian notation and CBOR.
=> Witness spec: minor editorial plus added links for CBOR and Endians

witness.md
This overhaul of the witness spec is heavily based on the existing spec. Major changes include (i) different notation, (ii) defining semantics alongside each syntax rule, and (iii) a switch from postfix format to prefix format, for example from `child child ... child branch` to `branch child child ... child`.
Thanks to @mandrigin, @AlexeyAkhunov, @axic, and @Raghavendra-PegaSys for feedback on the [draft](https://notes.ethereum.org/dfeV_C-pSI2h378AadR9DQ?view) of this pull request.
=> Overhaul witness spec

README.md, witness.md
As @poemm noticed, the witness document became too bloated, so I moved some introductory pieces from there to README.md.
I also added links to the docs in the repo and some more material.
=> Create a more comprehensive README for the repo

witness.md
Though it is apparent, I thought it might be better to have it stated that the grammar is unambiguous. Feel free to move it into a separate appendix of sorts, if anybody thinks that this document gets bloated.
=> unambiguity

witness.md
I did a simplification of the witness doc by merging use-cases and motivation to "objectives".
Also, numbering is nice to be able to discuss each part separately.
=> Add numbering and merge use cases and objectives.

witness.md
Thoughts on changing the integer encoding to big-endian?
Everywhere else that I know of uses big-endian (like all the storage, balance, nonce, etc fields). Is there a benefit to introducing a different encoding that I'm missing?
=> Switch integer encoding to big-endian

witness.md
This adds an option to encode an account with codesize and codehash, but without code. This is useful for the case when an account is "touched", but not executed.
However, if we were to change the meaning of `Bytecode` to "merkleized-bytecode", then it would be preferable to encode `codesize` and `codehash` next to the merklized bytecode, otherwise in most cases,  all code needs to be submitted.
=> Witness: add option to encode account with codesize/codehash but witout code

witness.md
Some minor format changes:
* Remove each leaf's `pathnibbles`, since these nibbles can be recovered by hashing the key or address.
* Remove `0xbb`, addressing https://github.com/ethereum/stateless-ethereum-specs/issues/24. (The `<Metadata>` byte gives enough flexibility for now.)
* Move all bytecode related stuff into `<Bytecode>`, including whether to parse code or codehash.
* Add validity rule to `<Bytecode>` that code must be accessed if it is included in the block, otherwise include just codehash.
* Fix typo in account node from `<Account_Storage_Tree_Node(0)>` to `<Tree_Node(0,1)>`.
Changes were implemented in [this commit](https://github.com/poemm/eth_witness_experiments/commit/5c69781d28638589787e48a90be696262d74e325). Tests pass.
=> Witness: some minor format changes

witness.md
This patch does _not_ change the binary encoding. It makes the definitions more concise, clear, and readable.
* Merge bullet-points for bracket `[` `]` notation, specifying the the special case for `bitmask` as an example.
* Clarify notation for semantics.
* Replace complicated syntax rules with validation rules. Allows completely removing some syntax rules like like `Bytes_More...`.
* Parentheses around arithmetic expressions, to avoid ambiguity.
* Clarify definition of `numbits()`.
* Clearer LEB128 description.
* Remove Metadata section, leaving the `0x00` byte to allow extending the witness spec with a metadata section or anything else.
* Finish `:=`->`::=` conversion, and reallign some rules after extra space for `::=`.
=> Witness: clean up, conciseness, clarity.

README.md
Hi, the Discord link in the README was blank, so I went on "[Ethereum 2.0 Devs Handbook and FAQs](https://notes.ethereum.org/@serenity/handbook)" and I filled out the invitation link that is there. 
I'm sorry if for some reason you have left it blank :)
=> Add Discord invitation link

portal-bridge-nodes.md
Include design and rationale for bridge nodes in the portal network. This document was originally created by @lithp [here](https://notes.ethereum.org/@lithp/r1NB6M4Gu) and is the same with a small update to the return type for `bridge_getBlockChanges()` suggested by @carver.
=> Include rationale and design for portal network bridge node jsonrpc api

portal-bridge-nodes.md
Improve return types for `bridge_getBlockChanges`. 
re: https://github.com/ethereum/stateless-ethereum-specs/pull/55#discussion_r618781966
=> Update bridge_getBlockChanges return type

state-network.md
ENR specification has this as `uint64` specified, see https://github.com/ethereum/devp2p/blob/master/enr.md#record-structure
ddht had this changed also recently in https://github.com/ethereum/ddht/pull/346
So lets use uint64 consistently for the ENR sequence number.
=> Adjust enr_seq to uint64 instead of uint32

state-network.md
Fix some minor but confusing mistakes.
Note: This does not resolve yet the issue of how to handle multiple Nodes response messages from the base layer perspective, that is, the resulting multiple talkresp messages (see second part of the issue description https://github.com/ethereum/stateless-ethereum-specs/issues/61)
=> Fix mistakes with message payload and Nodes total definition

portal-bridge-nodes.md
Add a section to bridge node api outlining the experimental api used by the nethermind bridge plugin. 
Coming soon will be a section outlining the initial testnet design, how other nodes can connect and access the testnet / plugin
=> Add experimental bridge node api

state-network.md
The current state network spec has not been updated with the latest network changes
- document that data is stored in two different formats
- document the content key and content-id formulas for both trie nodes and leaf proofs
- document the gossip mechanism
=> Update state network spec

beacon-chain/README.md, beacon-chain/beacon-state-dht.md, beacon-chain/beacon-state-network.md, beacon-chain/sync-gossip.md, portal-wire-protocol.md
This spec PR proposes two new sub-networks. One is for syncing headers of the beacon state, and the other is for asking questions about the state.
The main part of the PR is about the message formats of each sub-networks. It primarily leverages SSZ. The networking layer follows the portal network protocol.
=> Beacon chain spec

portal-wire-protocol.md
This adds explicit `selector`/`value` definitions for the `Union` defined for the payload of the `CONTENT` message in the wire spec as this was left vague.
=> Add selector definitions for `CONTENT` payload

portal-wire-protocol.md, portal-wire-test-vectors.md
Adding some basic test vectors to resolve https://github.com/ethereum/portal-network-specs/issues/101 
These were generated with the Fluffy implementation (this branch: https://github.com/status-im/nimbus-eth1/tree/use-ssz-union) and the test cases can also be seen/run from this test: https://github.com/status-im/nimbus-eth1/blob/use-ssz-union/fluffy/tests/test_portal_wire_encoding.nim.
That branch *should* implement the latest Portal wire specification, but there might be mistakes obviously. If something looks odd or is unclear, let me know.
=> Add basic test vectors for the Portal wire protocol

beacon-chain/beacon-state-network.md, beacon-chain/skip-sync-network.md, beacon-chain/sync-gossip.md
This modifies the spec to address some issues raised in the previous PR
https://github.com/ethereum/portal-network-specs/pull/99
1. How to initialize the first sync?
2. What happen if a client has an outdated snapshot?
=> Skip sync and initial sync

transaction-gossip.md
The transaction gossip spec was vague on how the radius mechanism should work.
Document how nodes should maintain their secondary routing table and use it for gossip.
=> Update tx gossip spec to include secondary routing table

history-network.md
- Change the `content-key` to an SSZ union
- Move `content-id` below `content-key` and add clarifications
=> Change History Network Content-Key to SSZ Union

utp-wire-test-vectors.md
Add test vectors for utp packets decoding and encoding. Most of of packets was generated by interaction with utp reference implementation.
=> Add test vectors for uTP encoding/decoding

content-keys-test-vectors.md
These are a set of test vectors for content keys encoding/decoding in SSZ for both state and history networks. One concern is that for the history network keys, in the spec, currently `content_type` is still part of the container. However, after some discussion, we decided to take it out of the SSZ container and just prefix it as the first byte when converting a key to bytes. This is why in the test vectors `content_type` is left out of input parameters.
UPDATE:
=> test vectors for content keys encode/decode

history-network.md
Some basic updates to the spec.
- Update to label the data as "Execution"
- *loosely* define RLP structures for headers, bodies, receipts.
- formatting
=> Minor updates to history network spec

testnet.md
We've got several Fluffy nodes now running continuously to test with.
I've designated 4 of them to be bootstrap nodes (meaning their network key / ip combination should remain the same over the course of time).
=> Update testnet.md with Fluffy bootstrap nodes

README.md, canonical-indices-network.md, header-gossip-network.md, history-network.md, portal-wire-protocol.md, state-network.md, transaction-gossip.md
Editorial review and update of most spec documents:
- Adds spec for canonical indices network
- Change to use the prefix "Execution" for networks that deal with the execution chain in preparation for future inclusion of Beacon chain networks.
- Define the terms "network" and "sub-protocol" and how they are used within the specs
- Add list of supported JSON-RPC endpoints
- Unification of language in how the different networks are described within their specifications.
- Move some common logic into common "Algorithms" section within the core portal wire protocol document
=> Updates to state network spec

portal-wire-protocol.md, state-network.md
Moved sections on neighborhood gossip and POKE to the Portal wire
specification. Adjusted and removed parts in the Portal wire
specification that were already explaining similar concepts.
The neighborhood gossip explanation is specifically adjusted to be
now a mix of a local neighbors lookup and a network node lookup.
This is what is currently being done in Fluffy (practically, it is a mix of what was written in state network spec and portal wire, originally history network, spec).
It kind of takes the best of both worlds: no additional node lookup if it isn't needed, but still able to (theoretically) propagate a piece of content even if that content is gossiped from only 1 node initially (assuming this node is well connected in the network). 
One thing that it still might lack, is …
=> Move sections on neighborhood gossip and POKE + adjustments

header-gossip-network.md
It's important to define an actual limit for the max historical epochs we want to support in the header accumulator as different implementations selecting a different value will lead to accumulators having different hash tree roots (as discovered by Ultralight/Fluffy when trying to harmonize test outputs in #145).  There's nothing magical about 100,000 other than it was selected by the two teams as a starting point and 100,000 historical epochs would get us to 819,200,000 million blocks (still more than 50x the length of the current mainnet chain) and have a size of roughly 3MB.
=> Define length of max historical epochs in header gossip spec

portal-wire-protocol.md
Added a section on prefixing a varint to each content item as possible solution to be able to send multiple content items over the uTP stream after offer/accept request-response. This should be able to preserve the streaming capabilities versus e.g. an SSZ List.
I've specified it only for the offer/accept request response, as that is the only location where multiple items can be send over the uTP stream. But if preferred to be used over the whole line, it could also be applied for FindContent/Content (in which case I would move the section).
=> Add varint prefix to offer/accept content items send over uTP stream

content-keys-test-vectors.md, header-gossip-network.md, history-network.md
- Move accumulator to the history network
- Add definitions for content keys of master and epoch accumulator
- Add Serialization for accumulator content
- Add test vectors for accumulator content keys
This moves the accumulator definition from header gossip to the history network and adds the content keys as defined in https://github.com/ethereum/portal-network-specs/issues/153:
- One difference is that the content key for the master accumulator is directly a `Union` type.
Not sure what to do with `chain_id` at this point? Get rid of it everywhere or use it everywhere? For now I did neither and left it untouched :)
The history spec could probably use some reorganization after this and some text is redundant, but that is not the scope of this PR. Scope right now is defining accumulator …
=> Move accumulator to from header gossip to history network

jsonrpc/src/content/params.json, jsonrpc/src/content/results.json, jsonrpc/src/methods/history.json, jsonrpc/src/methods/state.json
This is a useful API for bridge nodes, to push content out to peers of a running portal client.
It seems that most clients have not built out both APIs and started using them (`portal_historyOffer` and `portal_historySendOffer`), so I am proposing that we repurpose `portal_historyOffer` for broad gossiping, and use `portal_historySendOffer` for testing out specific messages.
=> portal_historyOffer: send to interested peers

SPECIFICATION_TEMPLATE.md, history-network.md, portal-wire-protocol.md
Each of the network specifications was slightly different in structure, with some elements repeated across different specifications.
After working with these for a bit, it seems this is roughly the common structure:
- Title
- Overview
- Data Types
- List of data types
- Retrieval mechnisms
- Specification
- Distance Function
- Content ID Derivation Function
- Wire Protocol
- Protocol Identifier
- Supported Message Types
- `Ping.custom_data` & `Pong.custom_data` (if used)
- Routing Table
- Node State
- Data Types
- Algorithms
1. Created a template markdown document that can be used for specifications
2. Added some "stock" definitions to the main portal wire protocol specification so that they don't have to be repeated in individual specs
3. TODO: will update existing specs
=> Implement sub-protocol template for Portal Wire Protocol

jsonrpc/src/content/results.json, jsonrpc/src/methods/history.json, jsonrpc/src/methods/state.json
Adding the `portal_*LocalContent` endpoint to JSON-RPC specs. This endpoint is useful for interop testing to check if a client stored content in the local database.
=> jsonrpc: Add portal_*LocalContent` endpoint to JSON-RPC specs

jsonrpc/src/methods/history.json, jsonrpc/src/methods/state.json
Reorder the JSON RPC calls to make it more intuitive to find them.
- Order more consistently for discv5, history and state
- Order related calls close to each other
- Delete some duplicate calls: portal_*Accept and portal_*Content
I found it sometimes difficult to figure out which call I'm looking at / looking for. Hopefully this improves it a bit.
Aside from that, I'd be fine with removing all the `Send` versions of the calls. Fluffy does not support them as they are difficult to implement and would require quite some refactor. I don't see a good use case for them either. If other clients have the same view on this, it would make the spec also smaller / easier.
=> Reorder JSON RPC calls and delete duplicates

jsonrpc/src/content/results.json, jsonrpc/src/methods/history.json, jsonrpc/src/methods/state.json
The `portal_historyOffer` call had been altered to basically do neighborhoud gossip.
To make that clear, lets call it instead `portal_historyGossip` and make a `portal_historyOffer` call that only offers content to a specifically provided node.
=> JSON-RPC rename offer to gossip and add new offer call

state-network.md
limit the scope of the state network by removing the availability/gossip of arbitrary nodes in the state trie.
changes:
* remove type definitions for arbitrary account and storage trie nodes.
* remove `Nibbles` type definition as it is no longer needed to express arbitrary trie paths.
* adjust type selectors to account for type removals.
* remove staged gossip description. gossip occurs as it does in other networks. no special disassembly/assembly logic is necessary to propagate data types.
* remove note about availability of exclusion proofs.
=> remove individual trie nodes from state spec

state-network.md
This updates the state spec in the following ways:
- Switches bitwise OR in Contract Bytecode `content_id` to byte concatenation for consistency with rest of `content_id` derivations (open to discussion on this but not obvious to me why we're using bitwise OR here - seems like it could lead to hash collision since there are plenty of possible `address`/`code_hash` that would produce the same input to the hash
- Adds proposed types for the content of each content type
=> State Network revisions

discv5-utp.md
current uTP data transfer diagrams fail to render due to backward arrow `<--`, so here we swap the elements and use the forward arrow `-->`
=> fix uTP diagram render error

jsonrpc/src/content/results.json, jsonrpc/src/methods/history.json, jsonrpc/src/methods/state.json
The 0x for no content found is applicable for RecursiveFindContent and LocalContent calls. Make use of one ContentResult type for both these calls in the definition.
The use of `0x` instead 0f `0x0` is more in line with the existing execution layer JSON-RPC API, where `0x` is used for unformatted data (https://ethereum.org/en/developers/docs/apis/json-rpc/#unformatted-data-encoding).
=> Adjust JSON-RPC spec to return 0x when no content is found

jsonrpc/src/methods/discv5.json, jsonrpc/src/methods/history.json, jsonrpc/src/methods/state.json
The description of getENR and lookupEnr was not very different. Attempted to clarify that. I didn't write implementation details on how the fetching of the network needs to happen, as I'm not sure we want to do that, and if we do, perhaps a more general location for that would be better.
As is not clear how the seqNum parameter is to be used and how it is useful in the lookupEnr call, I've removed it.
=> Clarify getEnr and lookupEnr JSON-RPC and remote seqNum parameter

jsonrpc/src/content/params.json, jsonrpc/src/methods/discv5.json, jsonrpc/src/schemas/base_types.json, jsonrpc/src/schemas/portal.json
A bit of clean-up: there were several unused leftover types (probably from previous API endpoint removals) and some naming/description improvements.
=> JSON-RPC types cleanup

jsonrpc/src/content/results.json
Currently it was implied, due to the ConnectionId result, that the returned values are these of the CONTENT protocol call and that the uTP transfer was not done all or not awaited for. It is however more interesting to have a call that also does the data transfer over uTP.
Here the call gets adjusted to do the transfer over uTP, but the result still allows for returning ENRs when the data is not available, and to indicate whether a uTP transfer was used or not.
Looks like this in openrpc playground:
edit: new picture of how it looks after the additions of https://github.com/ethereum/portal-network-specs/pull/206/commits/1a462d57479feab46b4362dab04ea8d7a85e2186 and https://github.com/ethereum/portal-network-specs/pull/206/commits/e120d3a285c281cd4ee10e5a2d4774590fe6cfa2
=> Adjust the FindContent JSON-RPC call to also retrieve data over uTP

beacon-chain/beacon-state-network.md
The word leave is used instead of leaf
by renaming the usage of leave with leaf
=> Fix spelling mistakes in beacon-state-network.md

jsonrpc/src/content/results.json, jsonrpc/src/methods/history.json, jsonrpc/src/methods/state.json
To maintain consistency with find content responses, we should support a `utp_transfer` boolean in recursive find content responses.
=> Add utp transfer field to recursive find content result

portal-wire-protocol.md
Allow for the node to return its closest nodes instead of only nodes closer to the target id.
Thanks to @KolbyML for pointing out that Fluffy is not following spec on this: https://github.com/status-im/nimbus-eth1/issues/1658
I think this restriction will work more against the content lookups than it helps:
- Filtering of nodes need to be done anyhow on the client side. You cannot trust the list of ENRs returned + you might have already contacted some of them through another path.
- I believe it might cause extra hops in some scenarios when the closest node(s) don't have the data.
Hence I would suggest this change instead of adjusting Fluffy.
=> Be less restrictive on closeness of nodes returned on FindContent

beacon-chain/beacon-network.md
And additionaly adjustments linked to this such as:
- Random gossip
- No need to return closest nodes in case it doesn't have the content
=> Specify that nodes must store all beacon chain LC data

beacon-chain/beacon-network.md
Added for the `LightClientFinalityUpdate` and `LightClientOptimisticUpdate` types.
I'm not fully sure about this yet, but I think it is the better approach. Slots are added to the content keys so that nodes can decide not to accept offers when it turns out it is an old update. 
As a counter effect, they do have to provide the current slot when they want to actively request this data (polling approach). I think that is fine as slots are time based.
The other way would involve not adding it to the key, but then, on an offer, a receiving node would have to "guess" what is likely being offered based on the current timestamp.
=> Add slots in content keys for Portal beacon LC types.

portal-wire-protocol.md
In `Nodes` responses & `Content` responses (that consist of an enr list), the response should filter out the enr record for the node that made the request, and the responder.
=> Filter request & responding nodes from enr list responses

beacon-chain/beacon-network.md
There is some ambiguity in the spec related to the `optimistic_slot` in the  `LightClientOptimisticUpdate` key and this adds clarification that this slot should match the slot of the attested header in the requested `LightClientOptimisticUpdate` (which on best case will always be 1 slot behind the current slot as computed by the node's local clock).
=> Clarify slot to be used in `OptimisticUpdate` content key

beacon-chain/beacon-network.md, state-network.md
Content keys on different portal networks can and do have overlapping selectors. For example the first byte of a history header content key is `0x00` and the first byte of a beacon bootstrap content key is `0x00`. 
I'm proposing that, as convention, we un-overlap these selectors for the sake of clarity. I'm **not** proposing that we make it required that these not overlap, which would put a limit on the number of auxillary networks (eg ethstorage) that can be built in the future.
The motivation for doing this is the ambiguity that it removes. With overlapping selectors a given content key needs to always be accompanied by information about which network it belongs to, otherwise it means nothing to the parser/reader. I think that this ambiguity will become a frustration while …
=> Unique selector bytes for History, Beacon, and State networks

state-network.md
- *Removes* old **distance** formula
- TODO: Define **distance** to be same as History Network
- *Removes* Commentary on "cold node" problem
- *Replaces* `account_trie_proof` **data type**
- *Adds* `account_trie_node` **data type**
- *Replaces* `contract_storage_trie_proof` **data type**
- *Adds** `contract_trie_node` **data type**
- *Modifies* `contract_bytecode` **data type**
- *Defines* new functions:
- `combine_path_and_nodehash`
- `rotate`
- *Defines* **nibble** types
- `nibble`
- `NibblePair`
- `Nibbles`
**Also includes new TODOs for completing spec design**
=> State Network Updates 

state-network.md
Adds a definition of the "Recursive Gossip" mechanism back into the spec
=> Add definition of recursive gossip

state-network.md
More tweaks and adjustments to state nework spec.
=> More cleanup of validity language for proofs and formatting

state-network.md
Another round of language and formatting tweaks for state network specification.
=> more language and formatting tweaks for state network specification

state-network.md
Be a bit more specific about the order in which content should be gossiped in the state network.  Highest priority should be for content that is part of the "inception" round of gossip, and lowest to the content that would be covered by subsequent rounds of recursive gossip.
=> Improve language around state network bridge gossip content priority ordering

state-network.md
I've removed content_id definition from types and fixed language describing how content_id is derived.
We don't have content_id definition in other network specs too.
=> remove content_id definition from types + lang fix for content_id

state-network.md
- ~`account_trie_proof`~
- deleted*
- ~`contract_storage_trie_proof`~
- deleted*
- `account_trie_node`
- new*
- `contract_trie_node`
- new*
- `contract_bytecode`
- modified*
- **REQUEST** (*find_content*)
- `Trie Node`
- **OFFER**
- `Trie Node` + `Proof`
- ...
- ...
- ...
- ...
=> state_network spec updates

beacon-chain/beacon-network.md, history-network.md
Add python syntax highlighting to code and pseudocode in Portal history and beacon network specs. To allow for better readability.
=> Add python syntax highlighting to code and pseudocode

beacon-chain/beacon-network.md
Relevant issue that explains the why: https://github.com/ethereum/portal-network-specs/issues/253
=> Have historical_summaries with proof updated every epoch

history-network-test-vectors.md, history-network.md
We will have more than one header accumulator for verifying the canonicalness of history headers:
- the well-known "master accumulator" for verifying pre-merge headers.
- the "Capella accumulator" (the frozen `historical_roots` from beacon state) for pre-Capella and post-merge headers.
- the "historical summaries" accumulator for post-Capella headers.
This PR proposes to rename `MasterAccumulator` to `MergeAccumulator` to make the name less confusing and more clear.
=> refactor(history-network): rename master accumulator

beacon-chain/beacon-network.md
Adding the epoch number in the content key will allow us to reject the offer if historical summaries with current or newer epochs are already stored in DB.
=> refactor(beacon-network): add `epoch` field in  `HistoricalSummariesWithProof` content key

portal-wire-protocol.md
https://github.com/ethereum/portal-network-specs/pull/258#issuecomment-2112683906
^ 
relates to this PR https://github.com/ethereum/portal-network-specs/pull/258
Having all current* network protocol ids be aligned looks nice
Kim said he likes beacon as C, I am fine with C or F.
ping @morph-dev for review too
=> Update mainnet protocol ids to be aligned

portal-wire-protocol.md
We are approaching launching a pre-merge history mainnet for serving 4444's data.
With the idea of mainnet in mind that means distinguishing a test network for testing major features to protect against breakages on mainnet. Or for testing future networks like beacon and state which would now take the place on the testnet work.
To distinguish these networks we will use different discv5 talkreq protocol id's.
Currently we have mainnet running history and beacon, testing if we can propagate new blocks in a timely matter. But we currently don't have validation for the post-merge data.
The mainnet's purpose would only support strict validation of data. Unlike the flexibility a testnet provides where we don't require stringent rules. So we would move the testing of beacon to our testnet.
We …
=> docs: define testnet protocol identifier

beacon-chain/beacon-network.md
This explicitly adds the validation mentioned in step1 for https://github.com/ethereum/portal-network-specs/issues/296 and https://github.com/ethereum/portal-network-specs/issues/305
=> Add validation description for LightClientBootstrap + Update

history/history-network.md, portal-wire-protocol.md, transaction-gossip/transaction-gossip.md
This doesn't really change anything to what the clients currently have implemented.
Might want to review in the future some of the sizes of the ByteLists used but for now no functional change on this.
=> Remove ByteList alias and fix Nodes reply to 1 response max

history/history-network.md
This doesn't have any functional change as these were already added long time ago to the block body type but the overview text never got updated.
=> Add withdrawals to history network specs text

jsonrpc/src/content/results.json, jsonrpc/src/methods/beacon.json
Add basic beacon network endpoints to `JSON_RPC` specs. 
All of the endpoints are copy/paste from the history network except this one:
- I'm proposing adding `portal_beaconOptimisticStateRoot` endpoint that returns the hex encoded recent known beacon state root.
=> feat(json-rpc): add beacon network JSON-RPC endpoints

beacon-chain/beacon-network.md, history/history-network.md, portal-wire-protocol.md, state/state-network.md
A few renames to be consistent with consensus SSZ specs and also to be consistent within the different Portal network specifications.
=> Use the same SSZ types & names as defined in SSZ spec

history/history-network.md
Offshoot of this PR https://github.com/ethereum/portal-network-specs/pull/333 you can read for a deeper background or reasoning.
In the other PR I list Pro's and Con's of certain block index model's and in the end come to the conclusion that it would probably just make more sense to store these values in the History network, as the total storage size for these indexes will be around 22ish GB with proofs. Which is extremely small in comparison with the requirements to store block bodies and receipts which is around 749.94GB so I think it is well justified. 
In the same note we have previously discussed https://github.com/ethereum/portal-network-specs/pull/268 removing `epoch accumulator history network content type`, but decided not to due to not having a better solution during the time. …
=> Proposal for block header lookup via block number in the history network

.gitignore, jsonrpc/src/content/params.json, jsonrpc/src/methods/beacon.json, jsonrpc/src/methods/history.json, jsonrpc/src/methods/state.json, jsonrpc/src/schemas/portal.json
I am trying to write a Hive test for https://github.com/ethereum/trin/issues/1484, and I am sending offer values of 64 items. The current issue I am facing is all Portal clients don't implement a JSON-RPC command that can send more than 1 piece of content per offer.
Trin already does, though, and we call it `portal_historyWireOffer.` I believe Nick made it for internal testing, but I think it would be useful for all clients to implement it for hive.
I am not adding this command to State or Beacon due to the way it works. If we want it to work for the State Network, we should include the content value in the parameters. I think Nick didn't do this because the message would could be very big, which might be a bad idea? I'm unsure if that is an issue, though, if the limit is only 64 items. …
=> Update `portal_*Offer` jsonrpc call to accept multiple key-value pairs

.gitignore, jsonrpc/src/content/results.json, jsonrpc/src/methods/beacon.json, jsonrpc/src/methods/history.json, jsonrpc/src/methods/state.json
I recently started working on building a portal rpc client library to be used in Nimbus to fetch the history network data, headers, bodies and receipts from portal in preparation for EIP-4444. When implementing the code I realized that as a user of the portal RPC API it would be nice to have a higher level endpoint that is able to lookup the content in the local database first before trying to fetch the content from the network. 
Without this new endpoint I had to first call `portal_historyLocalContent`, and then if a not found error was returned then call `portal_historyRecursiveFindContent` to look up the content over the network. This works but doesn't store the fetched content in the local database unless I also call `portal_historyStore` after getting the content from the network …
=> Rename portal_*RecursiveFindContent to portal_*GetContent

history/history-network.md
The way for proving these blocks was already presented/discussed a while back and in the mean while we also have test vectors added thanks to @ogenev (https://github.com/ethereum/portal-spec-tests/pull/9), so I suggest that we start thinking about a path for activating this in the network.
Aside from potentially adjusting the description in this PR and having it implemented in the clients, we will also need changes to the bridges to build these proofs and, more importantly, discuss on how we will get rid of the old headers without the proof that might already live on the network. Hence, keeping this in draft for now.
=> Add HistoricalRootsBlockProof for merge till capella blocks

history/history-network.md
PR on top of https://github.com/ethereum/portal-network-specs/pull/287
In draft as this would require a stable Portal beacon network deployed to have access to the `historical_summaries`.
=> Add HistoricalSummariesBlockProof for headers from Capella onwards

README.md
Previous link is wrong, update to correct link
=> README/update:canonical-transaction-index-link

history/history-network.md
2^11 * 2^4 == 2^15 not 2^17. 32k was already correct.
=> Fix documentation of `MAX_ENCODED_UNCLES_LENGTH` value

state/state-network.md
Poke in the state network is feasible by passing in the parent offer when looking up content. The fetched state content is then combined with the parent offer to build the offer which is used in the poke.
I'm not aware of any reason why poke should still be disabled in the state network, so I suggest we re-enable it.
=> Add poke to state network spec

jsonrpc/src/content/results.json, jsonrpc/src/methods/beacon.json, jsonrpc/src/methods/history.json, jsonrpc/src/methods/state.json
I suggest that we rename the `portal_*Gossip` JSON-RPC endpoint to `portal_*PutContent` and also update the method definition to include storing the content in the local database after performing some basic validations.
Changes in this PR:
- Renamed `portal_*Gossip` JSON-RPC endpoint to `portal_*PutContent`
- Updated the endpoint spec definition to include validation and storage in the local db
This is a similar update to https://github.com/ethereum/portal-network-specs/pull/344. My reasoning for this change is that I think we should have a high level endpoint counterpart to `portal_*GetContent` with similar naming and implementation storing in the local database when it makes sense to do so.
=> Rename portal_*Gossip JSON-RPC endpoint to portal_*PutContent

history/history-network.md
fixes #336 
should probably depend on #291
We are going to move towards keeping unproven headers in a separate content type than the proven ones.  This is based on the discussion in #336 
We will refer to headers near the front of the chain that are not in a stable HistoricalSummaries as "ephemeral" headers.  Their only proving path is through tracing the `Header.parent_hash` through the chain of headers and anchoring to a trusted header.  This trusted header must come from an independent oracle (such as the portal beacon network).
All clients in the network will be assumed to have some quantity of these recent headers.  The Ping and Pong `custom_data` field will also be modified to include a new field that signals how many of these recent headers a client is holding.
Clients will need to …
=> Add ephemeral block headers to the history network spec

SPECIFICATION_TEMPLATE.md, beacon-chain/beacon-network.md, canonical-transaction-index/canonical-transaction-index-network.md, history/history-network.md, ping-payload-extensions/extensions/template.md, ping-payload-extensions/extensions/type-0.md, ping-payload-extensions/extensions/type-1.md, ping-payload-extensions/extensions/type-2.md, ping-payload-extensions/extensions/type-65535.md, portal-wire-protocol.md, state/state-network.md, transaction-gossip/transaction-gossip.md
I basically just expand on Kim's PR and flesh out the rest of it so it aligns with his idea of removing the extra SSZ serialization layer
=> Remove one SSZ seralization layer from ping extensions + clean up rest of spec

jsonrpc/src/content/results.json, jsonrpc/src/errors/errors.json, jsonrpc/src/methods/beacon.json
A suite of tests were just added to hive that test a client's ability to sync the beacon network. These are the endpoints/behavior that hive expects a client to support to pass the sync tests
=> Add beacon endpoint for finalized state root used in hive

jsonrpc/src/methods/beacon.json, jsonrpc/src/methods/state.json
I accidentally copied the `portal_*Ping` params to `portal_*Offer` this PR fixes it  https://github.com/ethereum/portal-network-specs/pull/369#discussion_r1997285499
=> Fix state and beacon portal_*Offer params

jsonrpc/src/content/results.json, portal-wire-protocol.md, portal-wire-test-vectors.md
A offer can be declined for various reasons, using a generic decline message is very cryptic which makes it immensely hard to understand why we can't find nodes to accept the content, without controlling a majority of the network and logging every single implementation which doesn't make sense due to the complexity.
=> Add detailed offer decline codes

beacon-chain/beacon-network.md, canonical-transaction-index/canonical-transaction-index-network.md, history/history-network.md, state/state-network.md, transaction-gossip/transaction-gossip.md
fixes https://github.com/ethereum/portal-network-specs/issues/376 but this problem was also in quite a bit more places so I fixed it wherever I seen it happening.
=> Fix broken relative links for `portal-wire-spec.md` and `beacon-network.md`

implementation-details-overlay.md, state/state-network.md
I found another issue with linking files, this one only affects viewing on github, unlike my last PR. Without `.md` works on my local Markdown reader, but not on github's so without `.md` these 2 show 404 pages while viewing on github.
So https://github.com/ethereum/portal-network-specs/issues/376 wasn't working for 2 distinct issues I guess
=> Fix add missing .md's to file links

portal-wire-protocol.md, protocol-version-changelog.md
In the near term future, the network will no longer be run solely by "us".  In this world, we need a network that allows us to roll out breaking changes without negatively impacting the health of the network.  For this, our clients need to be able to support multiple versions of the protocol concurrently.
Adding protocol versioning, and a mechanism for clients to signal and negotiate supported versions of the protocol.
=> Add protocol versioning to the specification

portal-wire-protocol.md
Hi! I replaced dead links pointing to `ping-custom-payload-extensions.md` with the correct `README.md` file in the `ping-extensions` directory.
ref rename: https://github.com/ethereum/portal-network-specs/commits/master/ping-extensions/README.md
=> fixed broken links in `portal-wire-protocol.md`

.github/workflows/deploy.yaml, .github/workflows/test.yaml
Artifact Actions v3 will be deprecated by January 30, 2025. GitHub has started temporarily failing workflows that haven't been updated ahead of this deadline. This PR updates the action versions accordingly, following the [official migration guide](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md).
=> Update github actions versions due to deprecation

history/history-network.md
We switched the order headers are sent in from when this was originally written, and this text wasn't updated to account for that change
=> Make ephemeral header neighborhood gossip details more clear

jsonrpc/src/methods/beacon.json, jsonrpc/src/methods/history.json, jsonrpc/src/methods/state.json, portal-wire-protocol.md
We/Trin don't implement this `RecursiveFindNodes requirement`, I noticed this during the Portal Summit. I don't think we should launch a RecursiveFindNodes to continue the `Neighborhood gossip`.
- I don't think it is needed to successfully perform `Neighborhood gossip`
- Doing `RecursiveFindNodes` would cause delays in propagating the data, which we should be able to propagate a BlockBody/Receipt across the whole network in 4 seconds or less.
Your Neighborhood would have the best view of the your Neighborhood, so I think it is counterproductive to RFN your neighborhood, when simply doing `Neighborhood gossip` would achieve the same end result, but without using RFN.
If a node knows less then N nodes, then it probably received content far from the contents Neighborhood due to the node …
=> Move `Neighborhood Gossip`'s `RecursiveFindNodes` requirement to `portal_*PutContent`

history/history-network.md
This results in having a ExecutionBlockProof for Bellatrix until Capella fork and ExecutionBlockProofDeneb for Deneb and onwards.
Reasoning:
When using a List, you can have 1 type, but in the end still have to do some custom validations such a length check before doing the verification, and these custom validations would also require updates in the future. So one might as well use Vectors to be explicit about the type and have potential invalid data fail already at SSZ deserialization.
=> Change ExecutionBlockProof to be a Vector instead of a List

beacon-chain/beacon-network.md
The proof for the historical_summaries field in the BeaconState changes for Electra.
We need to support both types of proof. But I think after the fork we can actually remove the old one as it makes no sense to provide still the older `historical_summaries`.
Not sure if I should use the naming as I did now due to this.
=> Add HistoricalSummariesWithProof for Electra

portal-wire-protocol.md
I want to add support for Sepolia for Trin. Sepolia supports pre-merge history so it is a good first Ethereum Testnet candidate
=> Add protocol identifiers for Sepolia

beacon-chain/beacon-network.md
We had never explicitly defined that this should only be provided when it is part of the finalized state.
=> Clarify that HistoricalSummaries must be from finalized state

history/history-network.md
Just saw this conversation, and figured I would suggest a change to avoid future ambiguity:
> deme: Ah, so this +8 padding is in every case? That is, also just a single block update? I had not interpreted the text like that before, but I can see that now.
> [1:06 PM] deme: I guess it makes sense, normally nodes would not accept all those anyhow.
> [1:09 PM] deme: "So normally this would be 1 header, unless a re-org occurred where multiple would be included. An additional 8 header's content keys, MUST be included in the Offer message as padding."
> This sentence made me originally interpret it as minimum 8 additional headers when a re-org occurred.
> [1:10 PM] Kolby ML: It is more so 1 + re-org-depth + 8
> [1:10 PM] Kolby ML: So most of the time the re-org-depth would be 0 
> [1:10 PM] …
=> docs: clarify ephemeral headers always include padding

beacon-chain/beacon-network.md
Updating the beacon spec as agreed during last team call (see [agenda](https://github.com/ethereum/pm/issues/1525) and [call notes](https://hackmd.io/ynlSQZG9QNaDPR2qhRZ2TA?view#May-12th-2025---Call-55)).
- response to `LightClientUpdatesByRange` doesn't have to contain all requested updates, but updates that are in the response must start at the beginning of the requested range and must be consecutive
-  `LightClientOptimisticUpdate` and `LightClientFinalityUpdate` update should be requested for the first missing slot, and reply should always be the latest available (as long as it's not older than the requested one)
=> beacon: UpdatesByRange don't have to be full, clarify FindContent logic

beacon-chain/beacon-network.md, history/history-network.md, portal-wire-protocol.md
Add a clarification that ephemeral content should be gossiped using random gossip algorithm.
I moved existing random gossip algorithm out of beacon network spec, and into portal-wire-protocol (next to neighborhood gossip)
Since some concerns were raised regarding efficiency of the algorithm the selects peers completely randomly, I created #404 that explores alternatives. Updating random gossip spec can be done in a separate PR, once we reach agreement.
=> Specify that ephemeral headers should use random gossip

.github/workflows/deploy.yaml
This PR updates the GitHub Actions workflow to use actions/setup-node@v4, the latest version of the Node.js setup action.
It provides improved compatibility with recent Node.js versions and includes the latest performance and security improvements.
Confirmed latest version: [actions/setup-node@v4.4.0](https://github.com/actions/setup-node/releases/tag/v4.4.0)
=> Update CI to use actions/setup-node@v4

verkle/verkle-state-network.md
Updating the Verkle spec according to the recent work.
- Simplified and updated some types
- Provided more clarifications where needed
- Added link to the implementation
=> Update Verkle spec

portal-wire-protocol.md, protocol-version-changelog.md
The current approach of specifying the chain doesn't scale well (imagine supporting all testnets, devnets, layer-2 networks, etc).
Better approach is to specify supported chain-id as part of the ENR.
We already have `pv` entry in the ENR to indicate "Supported Portal wire-protocol versions". It seems like the waste to have multiple ENR entries that are Portal specific. This pr proposes following:
- merge protocol version and chain-id into one entry
- I currently call it `p` but I'm open for better suggestions (preferably, not longer that 3 characters)
- remove `pv` entry (no longer needed)
- encode the min/max supported protocol versions and chain-id as a `rlp` list
- this allows us to add new fields at the end of the list without breaking decoding (if needed in future upgrades)
- …
=> Announce `chain-id` inside ENR (and merge with `pv` key)

.github/workflows/deploy.yaml
Bumped actions/setup-node from v4 → v5
Using the latest version ensures continued support, bug fixes, and compatibility improvements.
Official release: https://github.com/actions/setup-node/releases/tag/v5.0.0
=> Update GitHub Actions setup-node to v5
