ethereum/portal-network-specs

witness.md

Great work, Igor. This is a very minor suggestion to add a background section for new readers at the top of the document to give it some context. Please do check it for validity and alignment with the rest of the doc. Thanks.

Suggestion for a Background section

---

witness.md

This PR adds a new section to the witness spec.
This section describes the goals that the specification should achieve. That should help everyone to be on the same page about how to treat this document.

Add "Goals Of This Document" section

---

witness.md

Some typos. Nothing controversial.

witness typos

---

witness.md

Suggested changes are aimed at improving readability and fixing a couple of typos

Some reorganising, formatting and typos

---

witness.md

Towards conciseness, this PR merges similar syntax rules for account tree nodes and storage tree nodes. Only the leaf nodes are different, so they have separate rules. A new parameter flags whether we are in the account tree or a state tree.
This PR does not change the binary format, only the syntax rules. (A language can have multiple syntaxes. We choose a more concise syntax.)
This change was [implemented as a commit over the current version](https://github.com/poemm/eth_witness_experiments/commit/024c7fb1439af2a67273e2674d2ebae01fcb0e63). All tests still pass.

More concise syntax rules

---

witness.md

Addressing https://github.com/ethereum/stateless-ethereum-specs/issues/30 .
LEB128 was chosen over big-endian VLQ because it has less awkward syntax, it is less awkward to implement, and it is used elsewhere in the ecosystem. But big-endian VLQ would also be a reasonable choice. And this change is modular -- any integer encoding can easily be swapped-in by changing the definition of rule `<Integer(n)>`.
This change allows using LEB128 to encode balances and nonces, a size optimization.
An early implementation is here https://github.com/poemm/eth_witness_experiments/blob/integers_leb128/parse_generate_spec.py. Tests pass, but more tests are needed.
Don't merge yet. I still have to write more tests and generalize the notation to support this new rule.

Witness: LEB128 for integers

---

witness.md

Follow-up on https://github.com/ethereum/stateless-ethereum-specs/issues/10

Witness specification: Add note on hexary/binary trie support

---

witness.md

This is for a rare edge case when a child doesn't need to be hashed -- see Yellowpaper appendix D, function `n`, the case allowing encodings of children shorter than 32-bytes to be unhahsed.
Don't merge yet, I still have to implement this change and write tests.

witness: fix bug when the RLP encoding of a tree node has fewer than 32 bytes

---

discv5-utp.md
state-network.md

[WIP] Add first draft of state network spec

---

portal-network.md

Add overview page for "Portal Network"

Portal network overview

---

portal-network.md

Add chain history and canonical indices overviews to the portal network spec.

Add chain history and canonical indices overviews

---

portal-network.md

@pipermerriam is this what you had in mind? I left out technical terms and details such as radius, devp2p or anything about how the data is organized, but let me know if you meant something different. Thanks!

Add network functionality description for state and transaction gossip

---

README.md

The main introduction document for the portal network was ready for another round of refinement.
Tried to re-work things to be a cleaner "onboarding" experience, describing some things more explicitly and converging towards common language for describing similar things.i

Update main portal network introduction document

---

README.md
transaction-gossip.md

fixes #77
Need a formal spec for transaction gossip network
Converted the previous forum post to a local specification document.

Transaction Gossip Network specification

---

testnet.md

Initial bootnode enrs for the trin testnet.

Add initial bootnode enrs

---

state-network.md

Use SSZ Union in Content Key serialization specification to be consistent in SSZ Union usage for serialization that uses a type prefix (i.e. portal wire spec). Shouldn't change actual serialization.

Use SSZ Union for state network content keys

---

testnet.md

Add Ultralight to list of clients and formatting cleanup

Testnet docs cleanup

---

jsonrpc/README.md

Update assembled json-rpc specs link

Fix assembled json-rpc specs link

---

jsonrpc/src/content/results.json
jsonrpc/src/methods/history.json
jsonrpc/src/methods/state.json

Add a RPC to request that the destination perform a content lookup for the given content key.

Add recursive content lookup RPC

---

history-network.md

This PR updates the history spec to attempt to be inline with what current implementations are doing or to reflect agreed upon changes that need to be implemented by clients.
- Remove `chain-id` from all content key types.
- Remove the *global* definition of how `content_key` is derived in favor of explicit encoding that doesn't implicitly rely on SSZ encoding semantics.  (Implementations should still be able to implement things as an SSZ Union if they would like).
- Add a `content_key` definition to every data type supported by the network.
- Remove the "master accumulator" as a network supported data type.
- Update language around the accumulator to specifically denote that it is for pre-merge blocks only.
- Minor wording changes.

Update history spec

---

history-network.md
state-network.md

The state network spec wasn't up-to-date with the latest format introduced in #168 
I converted it.

update state network spec to match template

---

README.md

One more remaining reference to header gossip.

remove remaining header gossip network

---

jsonrpc/README.md
jsonrpc/src/content/results.json
jsonrpc/src/methods/discv5.json
jsonrpc/src/methods/history.json
jsonrpc/src/methods/state.json

As a bonus, add some help to the json readme for knowing the right version of nodejs and how to preview the outputted json-rpc spec.

Clarify that recursiveFindNodes is plural everywhere

---

jsonrpc/src/schemas/base_types.json
jsonrpc/src/schemas/portal.json

This is pretty much what the implementations are already doing.

Fix DataRadius as hex encoded uint256 instead of number

---

jsonrpc/src/content/params.json
jsonrpc/src/content/results.json

And removed unused ConnectionId type

Adjust connectionId to be bytes2 instead of number

---

beacon-chain/light-client-network.md

We need a way to verify the canonicalness of post-merge execution block headers. 
1. Define `HistoricalSummaries` data
- The `BeaconState` field `historical_summaries` (`historical_roots` before Capella) provides an ongoing accumulator for Merkle roots of recent history logs. We can use this accumulator (with proof against the state root) to verify canonicalness for execution block headers older than 8192 slots (~27 hours).
2.  Move from the Beacon Chain Light Client Network narrative to the Beacon Chain Network, as not all of the data stored in the network is required by the light client protocol.

Add `HistoricalSummaries` to beacon chain network specs

---

portal-wire-protocol.md

Updating neighborhood gossip spec. Related to: https://github.com/ethereum/portal-hive/pull/97#discussion_r1321107440
This will reduce traffic multiplication.

Add 'SHOULD' spec to neighborhood gossip

---

state-network.md

Adds python functions and more precise definitions of content

some disperate changes

---

state-network.md

Add language to describe the path-aware content-id generation

Go into more detail about path aware content-id generation

---

state-network.md

This PR updates the state network spec to be *mostly* back in the same place it started, however, I've gone through and done a first pass at making sure all the content types are defined and removal of all of the path aware content-id generation stuff.

Remove path-aware content-id generation

---

state-network.md

Some refinement to serialization formats.

Better define serialization formats

---

state-network.md

Adding a bit more details regarding creation of correct values for the recursive gossip.

Clarify work required for the recursive gossip

---

history/history-network.md

This is how it looks if we bring in accordance with EIP-7643.

Update accumulator specs in accordance with eip-7643

---

history/history-network.md

Some had a double SSZ List encapsulation, of which one with the wrong limit set. Addtionality, renamed and restructured the (pseudo) code in attempt to be more clear.
Also changed 1 of the limits that was not being applied.

Correct and clarify history network type definitions

---

history/history-network.md

These are some of the format changes backported from the ethereum/EIPs PR https://github.com/ethereum/EIPs/pull/8630

update history-network.md to match ethereum/EIPs required formatting

---

ping-payload-extensions/ping-custom-payload-extensions.md
portal-wire-protocol.md

Removal of 1 ByteList to serialize / deserialize in the ping extensions format.

Remove one SSZ seralization layer from ping extensions

---

ping-payload-extensions/extensions/template.md
ping-payload-extensions/extensions/type-0.md
ping-payload-extensions/extensions/type-1.md
ping-payload-extensions/extensions/type-2.md
ping-payload-extensions/extensions/type-65535.md
portal-wire-test-vectors.md

Add tests for https://github.com/ethereum/portal-network-specs/pull/348

Add test vectors for ping extensions

---

portal-wire-protocol.md

Small PR - Commit 83fd2b638cf84c3ab35e9cb4a74731284927a2cd moved `discv5-utp.md`. This PR adjusts sources to changes. It also fixes a few typos along the way.

Update uTP SubProtocol source
